
export default {
  darkMode: "class",
  content: [
    "./public/landing/**/*.{html,js}",
    "./public/auth/**/*.{html,js,php}",
    "./public/admin/**/*.{html,js,php}",
    "./public/report/**/*.{php,js}",
    "./public/reports/**/*.{php,js}",
    "./public/animals/**/*.{php,js}",
    "./public/adoptions/**/*.{php,js}",
    "./public/listings/**/*.{php,js}",
    "./public/includes/*.php",
    "./public/{learning,messages,notifications}/**/*.{php,js}",
    "./public/js/**/*.{js,ts}",
  ],
  theme: {
    extend: {
      fontFamily: {
        display: ["Fraunces", "Georgia", "serif"],
        sans: ["Nunito", "system-ui", "-apple-system", "Segoe UI", "Roboto", "sans-serif"],
        mono: ['"IBM Plex Mono"', "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
      },
      colors: {
        paper: "hsl(var(--paper) / <alpha-value>)",
        paperdark: "hsl(var(--paperdark) / <alpha-value>)",
        ink: "hsl(var(--ink) / <alpha-value>)",
        jungle: "hsl(var(--jungle) / <alpha-value>)",
        jungle2: "hsl(var(--jungle2) / <alpha-value>)",
        coral: "hsl(var(--coral) / <alpha-value>)",
        teal: "hsl(var(--teal) / <alpha-value>)",
        stamp: "hsl(var(--stamp) / <alpha-value>)",
        border: "hsl(var(--border) / <alpha-value>)",
        input: "hsl(var(--input) / <alpha-value>)",
        ring: "hsl(var(--ring) / <alpha-value>)",
        background: "hsl(var(--background) / <alpha-value>)",
        foreground: "hsl(var(--foreground) / <alpha-value>)",
        primary: {
          DEFAULT: "hsl(var(--primary) / <alpha-value>)",
          foreground: "hsl(var(--primary-foreground) / <alpha-value>)",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary) / <alpha-value>)",
          foreground: "hsl(var(--secondary-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted) / <alpha-value>)",
          foreground: "hsl(var(--muted-foreground) / <alpha-value>)",
        },
        accent: {
          DEFAULT: "hsl(var(--accent) / <alpha-value>)",
          foreground: "hsl(var(--accent-foreground) / <alpha-value>)",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        card: {
          DEFAULT: "hsl(var(--card) / <alpha-value>)",
          foreground: "hsl(var(--card-foreground) / <alpha-value>)",
        },
        kpi: {
          jungle: "hsl(var(--kpi-jungle) / <alpha-value>)",
          "jungle-well": "hsl(var(--kpi-jungle-well) / <alpha-value>)",
          coral: "hsl(var(--kpi-coral) / <alpha-value>)",
          "coral-well": "hsl(var(--kpi-coral-well) / <alpha-value>)",
          sky: "hsl(var(--kpi-sky) / <alpha-value>)",
          "sky-well": "hsl(var(--kpi-sky-well) / <alpha-value>)",
          amber: "hsl(var(--kpi-amber) / <alpha-value>)",
          "amber-well": "hsl(var(--kpi-amber-well) / <alpha-value>)",
          ink: "hsl(var(--kpi-ink) / <alpha-value>)",
          "ink-well": "hsl(var(--kpi-ink-well) / <alpha-value>)",
          "trend-up": "hsl(var(--kpi-trend-up) / <alpha-value>)",
          "trend-down": "hsl(var(--kpi-trend-down) / <alpha-value>)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "var(--radius-xl)",
      },
    },
  },
  plugins: [],
};
